# Generated by Django 3.2.1 on 2021-05-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='operation',
        ),
    ]
